# -*- coding: utf-8 -*-
"""Projeto final estrutura de dados 2023.4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_qF28Ww_4SFT5hSDr5FOVGbDpiWyNq-y
"""

horarios = ["7:30 - 8:20", "8:20 - 9:10",
                       "9:10 - 10:00","10:20 - 11:10","11:10 - 12:00",
                       "12:00 - 12:50","13:00 - 13:50","13:50 - 14:40",
                       "14:40 - 15:30","15:50 - 16:40","16:40 - 17:30",
                       "17:30 - 18:20"]

dia = ["Segunda", "Terça", "Quarta", "Quinta", "Sexta"]

horarios_reservados = []

for i in range(len(dia)):
  print(dia[i])
  print(horarios)
  print("\n")

def fazerReserva():
  nomeProf = input("Nome professor:")
  contato = input("E-mail para contato:")
  nameCurs = input("Nome Curso:")
  periodo = input("Em qual período (Escrito por extendo, ex: Primeiro):")
  disciplina = input("Nome disciplina:")
  softwares = input("Quais programas serão necessários:")
  dia = input("Dia da semana para as aulas:")
  print("\n==================================\n")
  for i in range(len(horarios)):
    print(horarios[i])

  print("\n")
  horario = ("Escreva o horário que você deseja:")